CREATE TABLE "portfolioTable" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolioTable_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"user_id" text NOT NULL,
	"background_color" text NOT NULL,
	"emoji" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stockPerformance" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stockPerformance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"portfolio_id" integer NOT NULL,
	"stock_symbol" text NOT NULL,
	"average_cost" real DEFAULT 0 NOT NULL,
	"total_shares" real DEFAULT 0 NOT NULL,
	"total_cost" real DEFAULT 0 NOT NULL,
	"total_dividends" real DEFAULT 0 NOT NULL,
	"realized_profit" real DEFAULT 0 NOT NULL,
	"tax_and_broker_fee" real DEFAULT 0 NOT NULL,
	"total_inflow" real DEFAULT 0 NOT NULL,
	"total_outflow" real DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stockPerformance_portfolio_id_stock_symbol_unique" UNIQUE("portfolio_id","stock_symbol")
);
--> statement-breakpoint
CREATE TABLE "transactionTable" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transactionTable_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"portfolio_id" integer NOT NULL,
	"type" text NOT NULL,
	"transaction_date" date NOT NULL,
	"stock_symbol" text NOT NULL,
	"number_of_shares" real NOT NULL,
	"price_per_share" real,
	"dividend_per_share" real,
	"commission_and_taxes" real,
	"is_commission_percentage" boolean NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stockPerformance" ADD CONSTRAINT "stockPerformance_portfolio_id_portfolioTable_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolioTable"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactionTable" ADD CONSTRAINT "transactionTable_portfolio_id_portfolioTable_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolioTable"("id") ON DELETE cascade ON UPDATE no action;